# Generated by Django 6.0.2 on 2026-02-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arena_name', models.CharField(blank=True, default='', max_length=255)),
                ('time_zone', models.CharField(blank=True, default='', max_length=100)),
                ('date_format', models.CharField(blank=True, default='', max_length=100)),
                ('session_length', models.CharField(blank=True, default='', max_length=100)),
                ('session_presets', models.CharField(blank=True, default='', max_length=255)),
                ('allow_extension', models.BooleanField(default=False)),
                ('allow_reduction', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'General Setting',
                'verbose_name_plural': 'General Settings',
            },
        ),
    ]
