# Generated by Django 6.0.2 on 2026-02-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_generalsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_type', models.CharField(choices=[('solid', 'Solid Color'), ('gradient', 'Gradient'), ('image', 'Image')], default='solid', max_length=10)),
                ('background_value', models.CharField(blank=True, default='#F9FAFB', help_text='Hex color, CSS gradient, or leave blank when using image', max_length=500)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='themes/')),
                ('sidebar_bg', models.CharField(blank=True, default='#FFFFFF', max_length=20)),
                ('sidebar_text', models.CharField(blank=True, default='#4B5563', max_length=20)),
                ('sidebar_active_bg', models.CharField(blank=True, default='#F3F4F6', max_length=20)),
                ('sidebar_active_text', models.CharField(blank=True, default='#1F2937', max_length=20)),
                ('primary_color', models.CharField(blank=True, default='#CB30E0', max_length=20)),
                ('heading_font', models.CharField(blank=True, default='', max_length=100)),
                ('text_font', models.CharField(blank=True, default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Theme',
            },
        ),
    ]
