# Generated by Django 6.0.2 on 2026-02-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_dashboardtheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('cpu_usage', models.CharField(blank=True, default='', max_length=50)),
                ('storage_usage', models.CharField(blank=True, default='', max_length=100)),
                ('cpu_temperature', models.CharField(blank=True, default='', max_length=50)),
                ('ram_usage', models.CharField(blank=True, default='', max_length=50)),
                ('system_uptime', models.CharField(blank=True, default='', max_length=100)),
                ('voltage_power_status', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
