# Generated by Django 6.0.2 on 2026-02-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pendingsignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingsignup',
            name='rfid_tag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='session_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
