# Generated by Django 6.0.2 on 2026-02-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_pendingsignup_rfid_tag_pendingsignup_session_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingsignup',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendingsignup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('ended', 'Ended'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
