# Generated by Django 6.0.2 on 2026-02-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_pendingsignup_approved_at_alter_pendingsignup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingsignup',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
