# Generated by Django 6.0.2 on 2026-02-11 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_pendingsignup_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleared_at', models.DateTimeField(auto_now_add=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='accounts.controller')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='accounts.pendingsignup')),
            ],
            options={
                'ordering': ['cleared_at'],
                'unique_together': {('session', 'controller')},
            },
        ),
    ]
