# Generated by Django 6.0.2 on 2026-02-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_staffprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingsignup",
            name="ended_at",
            field=models.DateTimeField(
                blank=True, help_text="When the session was fully ended", null=True
            ),
        ),
        migrations.AddField(
            model_name="pendingsignup",
            name="is_playing",
            field=models.BooleanField(
                default=False,
                help_text="True if session is currently active (between start and stop)",
            ),
        ),
        migrations.AddField(
            model_name="pendingsignup",
            name="last_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Most recent start/resume time (null when paused)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pendingsignup",
            name="started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="First time the session was started (player began playing)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pendingsignup",
            name="total_elapsed_seconds",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Accumulated playtime in seconds across all start/stop cycles",
            ),
        ),
    ]
