# Generated by Django 6.0.2 on 2026-02-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_pendingsignup_ended_at_pendingsignup_is_playing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkpoint",
            name="points_earned",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total points earned for clearing this checkpoint (base + time bonus)",
            ),
        ),
    ]
