# Generated by Django 5.2.1 on 2026-02-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_checkpoint_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_type', models.CharField(choices=[('solid', 'Solid Color'), ('gradient', 'Gradient'), ('image', 'Image'), ('video', 'Video')], default='solid', max_length=10)),
                ('background_value', models.CharField(blank=True, default='#1a1a2e', help_text='Hex color, CSS gradient, or leave blank when using image/video', max_length=500)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='themes/app/')),
                ('background_video', models.CharField(blank=True, default='', help_text='Path to video file (e.g., /bgvideo.mp4)', max_length=255)),
                ('font_family', models.CharField(blank=True, default='', max_length=100)),
                ('font_color', models.CharField(blank=True, default='#FFFFFF', max_length=20)),
                ('button_color', models.CharField(blank=True, default='#CB30E0', max_length=20)),
                ('button_text_color', models.CharField(blank=True, default='#FFFFFF', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Theme',
                'verbose_name_plural': 'App Themes',
            },
        ),
    ]
