# Generated by Django 5.2.1 on 2026-02-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_apptheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptheme',
            name='background_video',
            field=models.FileField(blank=True, help_text='Video file for background (MP4, WebM, etc.)', null=True, upload_to='themes/app/'),
        ),
    ]
