# Generated by Django 6.0.2 on 2026-02-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_apptheme_background_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyline",
            name="hint",
            field=models.TextField(
                blank=True,
                default="",
                help_text="In-game hint shown to players during an active session at the station",
            ),
        ),
    ]
