# Generated by Django 6.0.2 on 2026-03-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_add_hint_to_storyline"),
    ]

    operations = [
        migrations.AddField(
            model_name="controller",
            name="station_host",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Station hardware WebSocket host (defaults to ip_address if empty)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="controller",
            name="station_port",
            field=models.PositiveIntegerField(
                default=8001, help_text="Station hardware WebSocket port"
            ),
        ),
    ]
