# Generated by Django 6.0.2 on 2026-03-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_controller_station_host_controller_station_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkpoint",
            name="elapsed_seconds",
            field=models.PositiveIntegerField(
                default=0, help_text="Time in seconds taken to complete this station"
            ),
        ),
        migrations.AddField(
            model_name="controller",
            name="is_end",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is the end/stop controller (last station)",
            ),
        ),
        migrations.AddField(
            model_name="controller",
            name="is_start",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is the start controller (first station)",
            ),
        ),
        migrations.AddField(
            model_name="pendingsignup",
            name="current_controller_index",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Index of the current controller station the player is at (0-based)",
            ),
        ),
        migrations.AlterField(
            model_name="checkpoint",
            name="points_earned",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Points earned = remaining seconds of the per-station countdown (in 10ths of minutes)",
            ),
        ),
    ]
