# Generated by Django 6.0.2 on 2026-04-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_checkpoint_elapsed_seconds_controller_is_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture for the staff member', null=True, upload_to='staff/'),
        ),
    ]
