# Generated by Django 6.0.3 on 2026-04-19 04:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_add_profile_picture_to_staffprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='hint_audio',
            field=models.FileField(blank=True, help_text='Audio file played as hint when hint button is pressed at this station', null=True, upload_to='hints/'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('signup_approved', 'Signup Approved'), ('signup_rejected', 'Signup Rejected'), ('session_ended', 'Session Ended'), ('session_time_added', 'Session Time Added'), ('session_time_reduced', 'Session Time Reduced'), ('session_points_updated', 'Session Points Updated'), ('checkpoint_added', 'Checkpoint Added'), ('checkpoint_removed', 'Checkpoint Removed'), ('staff_created', 'Staff Created'), ('staff_updated', 'Staff Updated'), ('staff_deleted', 'Staff Deleted'), ('staff_blocked', 'Staff Blocked'), ('staff_unblocked', 'Staff Unblocked'), ('settings_updated', 'Settings Updated'), ('controller_created', 'Controller Created'), ('controller_updated', 'Controller Updated'), ('controller_deleted', 'Controller Deleted'), ('storyline_created', 'Storyline Created'), ('storyline_updated', 'Storyline Updated'), ('storyline_deleted', 'Storyline Deleted')], max_length=50)),
                ('target_type', models.CharField(blank=True, default='', help_text='Type of object affected (e.g. PendingSignup, Controller)', max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, help_text='ID of the affected object', null=True)),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable description of the action')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data about the action')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
