# Generated by Django 6.0.3 on 2026-04-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_add_auditlog_and_hint_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='leaderboard_auto_rotate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='leaderboard_default_filter',
            field=models.CharField(choices=[('active', 'Active Sessions'), ('7days', 'Past 7 Days'), ('all', 'All Time')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='leaderboard_rotation_minutes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
