# Generated by Django 5.0.7 on 2026-04-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_controller_station_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='points_earned',
            field=models.PositiveIntegerField(default=0, help_text='Points earned = remaining seconds of the per-station countdown (1 second = 1 point)'),
        ),
    ]
